/*Generated by GenerateWrappers.py*/
#ifndef _WrapperToggleButton_H_
#define _WrapperToggleButton_H_
#include "sgl_types.h"
#include "sglConstants.h"
/* Pointer::ON_RELEASED/ */
#define ON_RELEASED_Pointer 2

/* Pointer::CLICKBUTTON/ */
#define CLICKBUTTON_Pointer 1

/* Pointer::TABLET_BUTTON/ */
#define TABLET_BUTTON_Pointer 0



/* ========================  input structure  ====================== */
typedef struct {
  SGLint32 /* @1/EmitCondition/, EmitCondition/, _L34/ */ EmitCondition;
  SGLbool /* @1/CursorIn/, @1/_L2/, MouseInside/, _L17/ */ MouseInside;
  SGLbool /* @1/MousePressed/,
     @1/_L15/,
     @4/RE_Input/,
     @4/_L1/,
     MousePressed/,
     _L15/ */ MousePressed;
  SGLbool /* @1/MouseReleased/, MouseReleased/, _L16/ */ MouseReleased;
  SGLint32 /* @1/MouseButton/, @1/_L1/, MouseButton/, _L126/ */ MouseButton;
  SGLbool /* @5/Init/, ToggleState/, _L148/ */ ToggleState;
  SGLbool /* SetToggleState/, _L151/ */ SetToggleState;
  SGLbool /* KeyEvent/, _L154/ */ KeyEvent;
} inC_ToggleButton;

/* =====================  no output structure  ====================== */

/* ========================  context type  ========================= */
typedef struct {
  /* ---------------------------  outputs  --------------------------- */
  SGLbool /* @3/IsSet/, StateChangeEmit/, _L152/ */ StateChangeEmit;
  SGLbool /* @5/State/, StateChangeValue/, _L150/ */ StateChangeValue;
  /* -----------------------  no local probes  ----------------------- */
  /* ----------------------- local memories  ------------------------- */
  SGLbool init;
  SGLbool /* @1/IfBlock1:then:_L4/ */ _L4_MouseClicked_1_then_IfBlock1;
  SGLbool /* @1/IfBlock1:then:_L5/,
     @2/IsSet/,
     @2/_L5/ */ _L5_FlipFlopS_1_MouseClicked_1;
  SGLbool /* @3/_L5/ */ _L5_FlipFlopS_1;
  /* -------------------- no sub nodes' contexts  -------------------- */
  /* ----------------- no clocks of observable data ------------------ */
} outC_ToggleButton;

extern void ToggleButton(inC_ToggleButton *inC, outC_ToggleButton *outC);

extern void ToggleButton_reset(outC_ToggleButton *outC);


typedef struct {
  outC_ToggleButton SSctx;
} wrapper_ToggleButton_mem;
#endif
