/*Generated by GenerateWrappers.py*/
#include "wrapper_ToggleButton_mem.h"

#include "sgl.h"
extern  SGLbool BHVR_AsynchronousACK;

/* ToggleButton/ */
void ToggleButton(inC_ToggleButton *inC, outC_ToggleButton *outC)
{
  SGLbool tmp;
  /* @1/IfBlock1:, @3/Set/, @3/_L1/, @5/Event/, MouseClicked/, _L149/, _L155/ */
  SGLbool MouseClicked;

  if (inC->SetToggleState) {
    outC->init = SGL_TRUE;
  }
  MouseClicked = inC->EmitCondition == ON_RELEASED_Pointer;
  /* @1/IfBlock1: */
  if (MouseClicked) {
    outC->_L5_FlipFlopS_1_MouseClicked_1 = (inC->MousePressed &
        ((inC->MouseButton == CLICKBUTTON_Pointer) | (inC->MouseButton ==
            TABLET_BUTTON_Pointer)) & inC->MouseInside) |
      ((!outC->_L4_MouseClicked_1_then_IfBlock1) &
        outC->_L5_FlipFlopS_1_MouseClicked_1);
    outC->_L4_MouseClicked_1_then_IfBlock1 = inC->MouseReleased;
    tmp = outC->_L5_FlipFlopS_1_MouseClicked_1 & inC->MouseInside &
      inC->MouseReleased;
  }
  else {
    tmp = inC->MousePressed & ((inC->MouseButton == CLICKBUTTON_Pointer) |
        (inC->MouseButton == TABLET_BUTTON_Pointer)) & inC->MouseInside;
  }
  MouseClicked = inC->KeyEvent | tmp;
  /* @5/State= */
  if (outC->init) {
    outC->init = SGL_FALSE;
    tmp = inC->ToggleState;
  }
  else {
    tmp = outC->StateChangeValue;
  }
  outC->StateChangeValue = MouseClicked ^ tmp;
  outC->StateChangeEmit = MouseClicked | ((!BHVR_AsynchronousACK) &
      outC->_L5_FlipFlopS_1);
  outC->_L5_FlipFlopS_1 = outC->StateChangeEmit;
}


void ToggleButton_reset(outC_ToggleButton *outC)
{
  outC->_L4_MouseClicked_1_then_IfBlock1 = SGL_FALSE;
  outC->_L5_FlipFlopS_1_MouseClicked_1 = SGL_FALSE;
  outC->_L5_FlipFlopS_1 = SGL_FALSE;
  outC->init = SGL_TRUE;
}

void wrapper_ToggleButton_reset(wrapper_ToggleButton_mem* mem)
{
  ToggleButton_reset(&(mem->SSctx));
}

void wrapper_ToggleButton(SGLint32 EmitCondition,
SGLbool MouseInside,
SGLbool MousePressed,
SGLbool MouseReleased,
SGLint32 MouseButton,
SGLbool ToggleState,
SGLbool SetToggleState,
SGLbool KeyEvent,
SGLbool (*StateChangeEmit),
SGLbool (*StateChangeValue),
wrapper_ToggleButton_mem* mem)
{
  inC_ToggleButton SSinputs;

  SSinputs.EmitCondition=EmitCondition;
  SSinputs.MouseInside=MouseInside;
  SSinputs.MousePressed=MousePressed;
  SSinputs.MouseReleased=MouseReleased;
  SSinputs.MouseButton=MouseButton;
  SSinputs.ToggleState=ToggleState;
  SSinputs.SetToggleState=SetToggleState;
  SSinputs.KeyEvent=KeyEvent;

  ToggleButton(&SSinputs,&(mem->SSctx));

  *StateChangeEmit = mem->SSctx.StateChangeEmit;
  *StateChangeValue = mem->SSctx.StateChangeValue;
}