
exclude: |
  (?x)^(model/)

repos:

  - repo: https://github.com/ansys/pre-commit-hooks
    rev: v0.5.2
    hooks:
      - id: add-license-headers
        args:
        - --start_year=2024

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: trailing-whitespace
    - id: check-yaml
    - id: requirements-txt-fixer

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-github-workflows
        name: "Check GitHub workflows"
        files: ^\.github/workflows/
        types: [yaml]
